### ISSUE TITLE
FPP Connect assumes port 80, cannot connect to any other port

### ISSUE THREAD

**Issue by EvilfishInsane** [xLightsSequencer/xLights#4449]
**Describe the bug**
I am using the FPP player through the [docker image](https://hub.docker.com/r/falconchristmas/fpp#!). I deployed the docker in my system, and after some setup, I tried to connect to it through the FPP Connect option under Tools.

When I entered my IP for the player with port `192.168.1.89;2412` nothing happens. If I tried just with the IP I do get a brief loading box:

![image](https://github.com/xLightsSequencer/xLights/assets/157799889/5f05ea29-f790-4ec2-b201-779bcf4e2dac)

But nothing happens, but this was kind of expected as the port was not 80. If I change the port to 80 in my docker system, then it works fine:

![image](https://github.com/xLightsSequencer/xLights/assets/157799889/8354c8da-7f59-444e-b801-43f50efcc013)

Now, yes, I could just use port 80, but as I might have some plans that need port 80 for something else, this is suddenly a problem. Could we include the possibility to use a port number to connect to a FFP running in a docker container?

**To Reproduce**
These steps assumes that a docker container system is installed and running. Also make sure firewall is not an issue.
0. Pull the container
``` bash
docker pull falconchristmas/fpp
```
1. Start FFP container with port exposing port 2412 or something none 80 for ease docker-compose.tml provided:
```yml
version: '3'
services:
  fpp:
    image: falconchristmas/fpp
    ports:
      - "2412:80"
    volumes:
      - type: bind
        source: <pathToLocalDirectory>
        target: /home/fpp/media
```
```bash
sudo docker-compose up -d
```
2. Try to connect to falcon player from xlight using the FPP Connect. Try with and without port. Observe no connection.
3. Shut down the container
```bash
sudo docker-compose down
```
4. Edit the docker-compose file:
```yml
version: '3'
services:
  fpp:
    image: falconchristmas/fpp
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: <pathToLocalDirectory>
        target: /home/fpp/media
```
5. Start container again
```bash
sudo docker-compose up -d
```
6.  Try to connect to falcon player from xlight using the FPP Connect, see it works.

**Expected behavior**
I would have liked to see that if you search for FFP at x.x.x.x:port and the port was anything else than 80, then it would work.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2024.06 64 bit
